ignored:
    - DL3018 # Pin versions in apk add - See: https://github.com/hadolint/hadolint/wiki/DL3018
    - SC2086 # For now I had troubles to do a proper quoting for PHPIZE_DEPS - See: https://github.com/koalaman/shellcheck/wiki/SC2086
    - DL3003 # To avoid creating more layers when installing composer packages this is allowed
    - DL4006 # False positive when piping git archive to tar extraction
