version: '3.2'
services:
  php_cli:
    image: usabillabv/php:7.2-cli-alpine3.8
    command: 
      - "-r"
      - "while (true){};"
    networks:
      - backend-php
  php_fpm:
    image: usabillabv/php:7.2-fpm-alpine3.8
    volumes:
      - fpm-sock:/var/run
      - ./test/functional/web:/var/www/html
    networks:
      - backend-php
  nginx:
    image: usabillabv/php:nginx
    ports:
      - 8080:80
    volumes:
      - fpm-sock:/var/run
    networks:
      - backend-php

volumes:
  fpm-sock:

networks: 
  backend-php:
